// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contest.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getContestSubmissions = `-- name: GetContestSubmissions :many
SELECT
    a.id AS account_id,
    a.name AS account_name,
    p.id AS problem_id,
    p.position AS problem_position,
    s.language,
    s.verdict,
    s.score,
    s.created_at
FROM submissions s
INNER JOIN problems p ON p.id = s.problem_id
INNER JOIN contests c ON c.id = p.contest_id
INNER JOIN accounts a ON a.id = s.account_id
WHERE p.contest_id = $1
  AND a.role = 'participant'
  AND a.is_banned = false
  AND s.created_at BETWEEN c.start_time AND c.end_time
ORDER BY a.id, p.position, s.created_at
`

type GetContestSubmissionsRow struct {
	AccountID       uuid.UUID
	AccountName     string
	ProblemID       uuid.UUID
	ProblemPosition *int32
	Language        Language
	Verdict         *Verdict
	Score           *float32
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) GetContestSubmissions(ctx context.Context, contestID uuid.UUID) ([]GetContestSubmissionsRow, error) {
	rows, err := q.db.Query(ctx, getContestSubmissions, contestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetContestSubmissionsRow
	for rows.Next() {
		var i GetContestSubmissionsRow
		if err := rows.Scan(
			&i.AccountID,
			&i.AccountName,
			&i.ProblemID,
			&i.ProblemPosition,
			&i.Language,
			&i.Verdict,
			&i.Score,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getContestTimeRange = `-- name: GetContestTimeRange :one
SELECT
    start_time,
    end_time
FROM contests
WHERE id = $1
`

type GetContestTimeRangeRow struct {
	StartTime pgtype.Timestamptz
	EndTime   pgtype.Timestamptz
}

func (q *Queries) GetContestTimeRange(ctx context.Context, contestID uuid.UUID) (GetContestTimeRangeRow, error) {
	row := q.db.QueryRow(ctx, getContestTimeRange, contestID)
	var i GetContestTimeRangeRow
	err := row.Scan(&i.StartTime, &i.EndTime)
	return i, err
}

const getContests = `-- name: GetContests :many
SELECT
    id,
    name,
    start_time AS start,
    end_time AS end
FROM contests
ORDER BY start_time
`

type GetContestsRow struct {
	ID    uuid.UUID
	Name  string
	Start pgtype.Timestamptz
	End   pgtype.Timestamptz
}

func (q *Queries) GetContests(ctx context.Context) ([]GetContestsRow, error) {
	rows, err := q.db.Query(ctx, getContests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetContestsRow
	for rows.Next() {
		var i GetContestsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Start,
			&i.End,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
