// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (email, password, name, school, student_id, phone_number)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type CreateAccountParams struct {
	Email       string
	Password    string
	Name        string
	School      *string
	StudentID   *string
	PhoneNumber *string
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.Email,
		arg.Password,
		arg.Name,
		arg.School,
		arg.StudentID,
		arg.PhoneNumber,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getAccountByEmail = `-- name: GetAccountByEmail :one
SELECT id, email, name, role, password, is_verified, is_banned
FROM accounts
WHERE email = $1
`

type GetAccountByEmailRow struct {
	ID         uuid.UUID
	Email      string
	Name       string
	Role       Role
	Password   string
	IsVerified bool
	IsBanned   bool
}

func (q *Queries) GetAccountByEmail(ctx context.Context, email string) (GetAccountByEmailRow, error) {
	row := q.db.QueryRow(ctx, getAccountByEmail, email)
	var i GetAccountByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.Password,
		&i.IsVerified,
		&i.IsBanned,
	)
	return i, err
}
