// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (email, password, name, school, student_id, phone_number)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type CreateAccountParams struct {
	Email       string
	Password    string
	Name        string
	School      *string
	StudentID   *string
	PhoneNumber *string
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.Email,
		arg.Password,
		arg.Name,
		arg.School,
		arg.StudentID,
		arg.PhoneNumber,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const isEmailRegistered = `-- name: IsEmailRegistered :one
SELECT EXISTS(
    SELECT 1
    FROM accounts
    WHERE email = $1
)
`

func (q *Queries) IsEmailRegistered(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, isEmailRegistered, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
