// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const getAccount = `-- name: GetAccount :one
SELECT email, name, role
FROM accounts
WHERE id = $1 AND is_banned = false
`

type GetAccountRow struct {
	Email string
	Name  string
	Role  Role
}

func (q *Queries) GetAccount(ctx context.Context, id uuid.UUID) (GetAccountRow, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i GetAccountRow
	err := row.Scan(&i.Email, &i.Name, &i.Role)
	return i, err
}

const getAccountByEmail = `-- name: GetAccountByEmail :one
SELECT id, email, name, password, role, is_banned
FROM accounts
WHERE email = $1
`

type GetAccountByEmailRow struct {
	ID       uuid.UUID
	Email    string
	Name     string
	Password string
	Role     Role
	IsBanned bool
}

func (q *Queries) GetAccountByEmail(ctx context.Context, email string) (GetAccountByEmailRow, error) {
	row := q.db.QueryRow(ctx, getAccountByEmail, email)
	var i GetAccountByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Password,
		&i.Role,
		&i.IsBanned,
	)
	return i, err
}
