// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: problem.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const getProblem = `-- name: GetProblem :one
SELECT p.position, p.name, p.content_path, p.time_limit, p.memory_limit
FROM problems p
WHERE id = $1
`

type GetProblemRow struct {
	Position    *int32
	Name        string
	ContentPath string
	TimeLimit   *int32
	MemoryLimit *int32
}

func (q *Queries) GetProblem(ctx context.Context, id uuid.UUID) (GetProblemRow, error) {
	row := q.db.QueryRow(ctx, getProblem, id)
	var i GetProblemRow
	err := row.Scan(
		&i.Position,
		&i.Name,
		&i.ContentPath,
		&i.TimeLimit,
		&i.MemoryLimit,
	)
	return i, err
}

const getProblemLanguages = `-- name: GetProblemLanguages :many
SELECT pl.language
FROM problem_languages pl
WHERE problem_id = $1
`

func (q *Queries) GetProblemLanguages(ctx context.Context, problemID uuid.UUID) ([]Language, error) {
	rows, err := q.db.Query(ctx, getProblemLanguages, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Language
	for rows.Next() {
		var language Language
		if err := rows.Scan(&language); err != nil {
			return nil, err
		}
		items = append(items, language)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
