// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: submit.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createSubmission = `-- name: CreateSubmission :one
INSERT INTO submissions (problem_id, account_id, language, code)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateSubmissionParams struct {
	ProblemID uuid.UUID
	AccountID uuid.UUID
	Language  Language
	Code      string
}

func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createSubmission,
		arg.ProblemID,
		arg.AccountID,
		arg.Language,
		arg.Code,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
