// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: submission.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSubmission = `-- name: CreateSubmission :one
INSERT INTO submissions (problem_id, account_id, language, code)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateSubmissionParams struct {
	ProblemID uuid.UUID
	AccountID uuid.UUID
	Language  Language
	Code      string
}

func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createSubmission,
		arg.ProblemID,
		arg.AccountID,
		arg.Language,
		arg.Code,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getSubmitHistory = `-- name: GetSubmitHistory :many
SELECT s.id, s.language, s.code, s.verdict, s.score, s.created_at
FROM submissions s
WHERE problem_id = $1 AND account_id = $2
`

type GetSubmitHistoryParams struct {
	ProblemID uuid.UUID
	AccountID uuid.UUID
}

type GetSubmitHistoryRow struct {
	ID        uuid.UUID
	Language  Language
	Code      string
	Verdict   *Verdict
	Score     *float32
	CreatedAt time.Time
}

func (q *Queries) GetSubmitHistory(ctx context.Context, arg GetSubmitHistoryParams) ([]GetSubmitHistoryRow, error) {
	rows, err := q.db.Query(ctx, getSubmitHistory, arg.ProblemID, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSubmitHistoryRow
	for rows.Next() {
		var i GetSubmitHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Language,
			&i.Code,
			&i.Verdict,
			&i.Score,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
