// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: test_cases.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createTestCase = `-- name: CreateTestCase :one
INSERT INTO test_cases (problem_id, input_path)
VALUES ($1, $2)
RETURNING id
`

type CreateTestCaseParams struct {
	ProblemID uuid.UUID
	InputPath string
}

func (q *Queries) CreateTestCase(ctx context.Context, arg CreateTestCaseParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createTestCase, arg.ProblemID, arg.InputPath)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
