// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (email, name, password, role)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateAccountParams struct {
	Email    string
	Name     string
	Password string
	Role     Role
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.Email,
		arg.Name,
		arg.Password,
		arg.Role,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
