// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Language string

const (
	LanguageRust   Language = "rust"
	LanguageCpp    Language = "cpp"
	LanguagePython Language = "python"
	LanguageJava   Language = "java"
	LanguageHtml   Language = "html"
)

func (e *Language) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Language(s)
	case string:
		*e = Language(s)
	default:
		return fmt.Errorf("unsupported scan type for Language: %T", src)
	}
	return nil
}

type NullLanguage struct {
	Language Language
	Valid    bool // Valid is true if Language is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLanguage) Scan(value interface{}) error {
	if value == nil {
		ns.Language, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Language.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLanguage) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Language), nil
}

type Role string

const (
	RoleParticipant Role = "participant"
	RoleJury        Role = "jury"
	RoleAdmin       Role = "admin"
)

func (e *Role) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Role(s)
	case string:
		*e = Role(s)
	default:
		return fmt.Errorf("unsupported scan type for Role: %T", src)
	}
	return nil
}

type NullRole struct {
	Role  Role
	Valid bool // Valid is true if Role is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRole) Scan(value interface{}) error {
	if value == nil {
		ns.Role, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Role.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Role), nil
}

type Verdict string

const (
	VerdictAccepted              Verdict = "accepted"
	VerdictWrongAnswer           Verdict = "wrong_answer"
	VerdictTimeLimitExceeded     Verdict = "time_limit_exceeded"
	VerdictCompilationError      Verdict = "compilation_error"
	VerdictMemoryLimitExceeded   Verdict = "memory_limit_exceeded"
	VerdictRuntimeError          Verdict = "runtime_error"
	VerdictIdleTimeLimitExceeded Verdict = "idle_time_limit_exceeded"
)

func (e *Verdict) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Verdict(s)
	case string:
		*e = Verdict(s)
	default:
		return fmt.Errorf("unsupported scan type for Verdict: %T", src)
	}
	return nil
}

type NullVerdict struct {
	Verdict Verdict
	Valid   bool // Valid is true if Verdict is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVerdict) Scan(value interface{}) error {
	if value == nil {
		ns.Verdict, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Verdict.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVerdict) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Verdict), nil
}

type Account struct {
	ID        uuid.UUID
	Email     string
	Name      string
	Password  string
	Role      Role
	IsBanned  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Contest struct {
	ID        uuid.UUID
	Name      string
	StartTime pgtype.Timestamptz
	EndTime   pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Problem struct {
	ID              uuid.UUID
	ContestID       uuid.UUID
	Position        *int32
	Name            string
	Content         string
	CheckerLanguage *Language
	CheckerPath     *string
	TimeLimit       *int32
	MemoryLimit     *int32
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type ProblemLanguage struct {
	ProblemID uuid.UUID
	Language  Language
}

type Submission struct {
	ID        uuid.UUID
	ProblemID uuid.UUID
	AccountID uuid.UUID
	Language  Language
	Code      string
	Verdict   *Verdict
	Score     *float32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type TestCase struct {
	ID        uuid.UUID
	ProblemID uuid.UUID
	InputPath string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
