// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: problem.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const assignProblemsToContest = `-- name: AssignProblemsToContest :execrows
UPDATE problems
SET contest_id = $1
WHERE id = ANY($2::uuid[])
  AND contest_id IS NULL
`

type AssignProblemsToContestParams struct {
	ContestID  uuid.UUID
	ProblemIds []uuid.UUID
}

func (q *Queries) AssignProblemsToContest(ctx context.Context, arg AssignProblemsToContestParams) (int64, error) {
	result, err := q.db.Exec(ctx, assignProblemsToContest, arg.ContestID, arg.ProblemIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProblemsByContest = `-- name: GetProblemsByContest :many
SELECT 
    id,
    position,
    name
FROM problems
WHERE contest_id = $1
ORDER BY position ASC
`

type GetProblemsByContestRow struct {
	ID       uuid.UUID
	Position *int32
	Name     string
}

func (q *Queries) GetProblemsByContest(ctx context.Context, contestID uuid.UUID) ([]GetProblemsByContestRow, error) {
	rows, err := q.db.Query(ctx, getProblemsByContest, contestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProblemsByContestRow
	for rows.Next() {
		var i GetProblemsByContestRow
		if err := rows.Scan(&i.ID, &i.Position, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProblemsForContestAssignment = `-- name: GetProblemsForContestAssignment :many
SELECT
    id,
    contest_id
FROM problems
WHERE id = ANY($1::uuid[])
`

type GetProblemsForContestAssignmentRow struct {
	ID        uuid.UUID
	ContestID uuid.UUID
}

func (q *Queries) GetProblemsForContestAssignment(ctx context.Context, problemIds []uuid.UUID) ([]GetProblemsForContestAssignmentRow, error) {
	rows, err := q.db.Query(ctx, getProblemsForContestAssignment, problemIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProblemsForContestAssignmentRow
	for rows.Next() {
		var i GetProblemsForContestAssignmentRow
		if err := rows.Scan(&i.ID, &i.ContestID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
