// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: submission.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getSubmissionsByContest = `-- name: GetSubmissionsByContest :many
SELECT
    s.id,
    p.name AS problem_name,
    a.name AS owner_name,
    s.language,
    s.verdict,
    s.score,
    s.created_at
FROM submissions s
JOIN problems p ON p.id = s.problem_id
JOIN accounts a ON a.id = s.account_id
WHERE p.contest_id = $1
ORDER BY s.created_at DESC
`

type GetSubmissionsByContestRow struct {
	ID          uuid.UUID
	ProblemName string
	OwnerName   string
	Language    Language
	Verdict     *Verdict
	Score       *float32
	CreatedAt   time.Time
}

func (q *Queries) GetSubmissionsByContest(ctx context.Context, contestID uuid.UUID) ([]GetSubmissionsByContestRow, error) {
	rows, err := q.db.Query(ctx, getSubmissionsByContest, contestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSubmissionsByContestRow
	for rows.Next() {
		var i GetSubmissionsByContestRow
		if err := rows.Scan(
			&i.ID,
			&i.ProblemName,
			&i.OwnerName,
			&i.Language,
			&i.Verdict,
			&i.Score,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
